dataset_path: json
dataset_kwargs:
  data_files:
    test: /mnt/sftp/data/multimodal_test_set/annotations/output_laion_en_sftp.jsonl
task: "laion_mcq_en"
test_split: test
process_docs: !function utils.laion_filter_valid_images
doc_to_visual: !function utils.laion_doc_to_visual
doc_to_text: !function utils.laion_doc_to_text
doc_to_target: "ground_truth"
process_results: !function utils.laion_process_results
metric_list:
  - metric: laion_mcq_acc
    aggregation: !function utils.laion_aggregate_results
    higher_is_better: true
include: _default_template_yaml
